CREATE DATABASE lazada;

CREATE TABLE users (
	Uid INT NOT NULL AUTO_INCREMENT,
	UName VARCHAR(50) NOT NULL,
	Adress VARCHAR(200),
	Longitude DECIMAL,
   	Latidtude DECIMAL,
   	Username VARCHAR(50) NOT NULL,
   	Pwd VARCHAR(255) NOT NULL,
	URole INT NOT NULL,
	PRIMARY KEY (Uid),
	UNIQUE (Username)
) ENGINE InnoDB;

CREATE TABLE products (
	Pid INT NOT NULL AUTO_INCREMENT,
	Pname VARCHAR(50) NOT NULL,
    Price DECIMAL NOT NULL,
    Vid  INT NOT NULL,
    PRIMARY KEY (Pid),
    FOREIGN KEY (Vid) REFERENCES users(Uid)
) ENGINE = InnoDB;
